name = "twopass"
main = "src/index.js"
compatibility_date = "2025-10-20"

[durable_objects]
bindings = [
  { name = "TCP_SESSION", class_name = "TCPSession" }
]

[[migrations]]
tag = "v1"
new_classes = ["TCPSession"]

[observability]
enabled = true

#[vars]
# Password used to protect tunnel requests.
# Set PASSWORD in Cloudflare Secrets instead of hardcoding it here.
#PASSWORD = "password"
