name = "lesspass"
main = "src/index.js"
compatibility_date = "2025-08-29"

[observability]
enabled = true

[vars]
# Used to authenticate with the V2Ray/Xray client.
# Set USER_ID in Cloudflare Secrets instead of hardcoding it here.
#USER_ID = "86c50e3a-5b87-49dd-bd20-03c7f2735e40"

# Password used to protect info requests.
# Set PASSWORD in Cloudflare Secrets instead of hardcoding it here.
#PASSWORD = "password"

# Proxy address to connect to the Cloudflare Network.
# Cloudflare Workers prohibit direct socket connections to Cloudflare IPs.
PROXY_ADDR = "bpb.yousef.isegaro.com:443"

# DNS-over-HTTPS url to use when resolving DNS queries.
DOH_URL = "https://1.1.1.1/dns-query"

# Determines the log level.
LOG_LEVEL = "INFO"
