name: Deno Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'Server/Deno/**'
      - '.github/workflows/deno-deploy.yml'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Deno Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Run Deno lint
        working-directory: ./Server/Deno
        run: deno lint src/
      
      - name: Run Deno fmt check
        working-directory: ./Server/Deno
        run: deno fmt --check src/

  test:
    name: Test Deno Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Run tests
        working-directory: ./Server/Deno
        run: deno test --allow-net --allow-env src/

  deploy:
    name: Deploy to Deno Deploy
    runs-on: ubuntu-latest
    needs: [lint, test]
    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: ${{ secrets.DENO_PROJECT_NAME }}
          entrypoint: src/index.js
          root: Server/Deno
