name: TwoPass Client Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
    paths:
      - 'TwoPass/Client/**'
      - '.github/workflows/client-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'TwoPass/Client/**'
  workflow_dispatch:

jobs:
  build:
    name: Build Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.3'
      
      - name: Build all architectures
        working-directory: ./TwoPass/Client
        run: make
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            TwoPass/Client/dist/twopass-*
            TwoPass/Client/dist/SHA256SUMS

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries
          path: dist
      
      - name: Create or Update Beta Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: Beta
          name: Beta Release
          prerelease: true
          files: |
            dist/twopass-*
            dist/SHA256SUMS
          body: |
            Automated beta build from latest commit
            Commit: ${{ github.sha }}
      
      - name: Create Tag Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/twopass-*
            dist/SHA256SUMS
          generate_release_notes: true
