name: TwoPass Cloudflare Workers Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'TwoPass/Server/Cloudflare/**'
      - '.github/workflows/cloudflare-deploy.yml'
  workflow_dispatch:

jobs:
  lint:
    name: Lint Cloudflare Worker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Install dependencies
        working-directory: ./TwoPass/Server/Cloudflare
        run: npm install
      
      - name: Run ESLint
        working-directory: ./TwoPass/Server/Cloudflare
        run: npx eslint src/ || true

  deploy:
    name: Deploy to Cloudflare
    runs-on: ubuntu-latest
    needs: [lint]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          workingDirectory: ./TwoPass/Server/Cloudflare
