name = "router"
main = "src/index.js"
compatibility_date = "2025-08-29"

[observability]
enabled = true

[vars]
# Define your routes as a JSON string.
# - "path": The URL prefix to match.
# - "backend": The URL of your backend.
#
# IMPORTANT: Order matters! Place more specific
# paths (/api/v1) before less specific ones (/).
CONFIG = '''
[
  { "path": "/tunnel/vless-ws", "backend": "https://lesspass.farelra.deno.net" },
  { "path": "/tunnel/trojan-ws", "backend": "https://tronpass.farelra.deno.net" },
  { "path": "/tunnel/h2", "backend": "https://twopass.farelra.deno.net" }
]
'''
